### PR TITLE
Umount all sandbox mountpoint

### LINKED ISSUE #629: Umount all sandbox mountpoint
When I use the chroot sandbox, not all mountpoints detached when the build finishes.

This allows to create malicious package that can destroy workers with a spec file build section like this: 
```
...
BuildRequires: sudo-for-abuild
...

%build
dd if=/dev/zero of=image.img iflag=fullblock bs=1M count=100 && sync
sudo losetup loop0 image.img
sudo mkfs -t ext4  /dev/loop0
sudo losetup -d /dev/loop0
mkdir error
sudo mount -o loop image.img error/
sudo mkdir error/proc
sudo mkdir error/parentroot
sudo mount -o loop image.img error/parentroot
sudo mount -t proc /proc error/proc
```

sudo may be enabled by another malicious package

Right after this package will be built, any other package will crash with following error:
```
[    1s] rm: WARNING: Circular directory structure.
[    1s] This almost certainly means that you have a corrupted file system.
[    1s] NOTIFY YOUR SYSTEM MANAGER.
[    1s] The following directory is part of the cycle:
[    1s]   /obswrk/root/home/abuild/rpmbuild/BUILD/rpm-helloword-1.1.0/error/parentroot
```

### PR DESCRIPTION
**Pull request by kvelichko-omp**
Fix #629

### CODE REVIEW

**Comment by marcus-h** [comment]
On 2020-11-23 07:22:22 -0800, kvelichko-omp wrote:
> diff --git a/build b/build
> index a637c54a..7725e070 100755
> --- a/build
> +++ b/build
> @@ -446,11 +446,7 @@ cleanup_and_exit () {
>  	test -n "$browner" && chown "$browner" $BUILD_ROOT
>  	vm_shutdown "$1"
>      else
> -	buildroot_umount /proc/sys/fs/binfmt_misc
> -	buildroot_umount /proc
> -	buildroot_umount /sys
> -	buildroot_umount /dev/pts
> -	buildroot_umount /dev/shm
> +	umount_stuff
>  	test -n "$VM_ROOT" -a "$VM_ROOT" != 1 && umount $BUILD_ROOT 2>/dev/null || true
>  	test -n "$VM_TYPE" && vm_cleanup
>      fi
> @@ -802,11 +798,9 @@ mount_stuff() {
>
>  umount_stuff() {
>      if test -n "$BUILD_ROOT" -a "$BUILD_ROOT" != / ; then
> -	buildroot_umount /proc/sys/fs/binfmt_misc
> -	buildroot_umount /proc
> -	buildroot_umount /sys
> -	buildroot_umount /dev/pts
> -	buildroot_umount /dev/shm
> +	while read -r mountpoint; do
> +	    umount -n $mountpoint 2>/dev/null || true
> +	done < <(awk '{print length($2) " " $2}' < /proc/mounts | sort -r -n | cut -d ' ' -f 2- | grep "^$BUILD_ROOT")

Hmm doesn't this fail if a mountpoint contains, for instance, a
whitespace " "? Consider the following code in a build description
(for instance, a spec file):

sudo mkdir "/my dir"
sudo ln -s /mnt "my\\040dir"
sudo mount -t proc none "/my dir"

With your proposed change, the /mnt mountpoint on the host system
will be umounted (if I'm not completely mistaken).

**Comment by kvelichko-omp** [comment]
Thanks for comment, fixed whitespace processing and extended my test stuff.


I extend build section of spec with commands:

```
...
BuildRequires: sudo-for-abuild
...

%build
dd if=/dev/zero of=image.img iflag=fullblock bs=1M count=100 && sync
sudo losetup loop0 image.img
sudo mkfs -t ext4  /dev/loop0
sudo losetup -d /dev/loop0
mkdir error
sudo mount -o loop image.img error/
sudo mkdir error/proc
sudo mkdir error/parentroot
sudo mount -o loop image.img error/parentroot
sudo mount -t proc /proc error/proc

sudo mkdir "/my dir"
sudo mkdir "/my\\040dir2"
sudo mkdir "/1 \n 2"
sudo ln -s /mnt "my\\040dir"
sudo mount -t proc none "/my dir"
sudo mount -t proc none "/my\\040dir2"
sudo mount -t proc none "/1 \n 2"
sudo cat /proc/mounts
```

it doesn't matter how many mountpoint links, only one mountpoint is added to /proc/mounts:
```
# cat /proc/mounts
....
 mqueue /dev/mqueue mqueue rw,nosuid,nodev,noexec,relatime 0 0
 shm /dev/shm tmpfs rw,nosuid,nodev,noexec,relatime,size=65536k 0 0
 /dev/mapper/kviset--vg-root /etc/resolv.conf ext4 rw,relatime,errors=remount-ro 0 0
 /dev/mapper/kviset--vg-root /etc/hostname ext4 rw,relatime,errors=remount-ro 0 0
 /dev/mapper/kviset--vg-root /etc/hosts ext4 rw,relatime,errors=remount-ro 0 0
 none /obswrk/root/dev/pts devpts rw,relatime,gid=5,mode=620,ptmxmode=000 0 0
 none /obswrk/root/dev/pts devpts rw,relatime,gid=5,mode=620,ptmxmode=000 0 0
 none /obswrk/root/proc proc rw,relatime 0 0
 none /obswrk/root/sys sysfs rw,relatime 0 0
 none /obswrk/root/dev/pts devpts rw,relatime,gid=5,mode=620,ptmxmode=000 0 0
 none /obswrk/root/dev/shm tmpfs rw,relatime 0 0
 /dev/loop0 /obswrk/root/home/abuild/rpmbuild/BUILD/rpm-helloword-1.1.0/error ext4 rw,relatime 0 0
 /dev/loop0 /obswrk/root/home/abuild/rpmbuild/BUILD/rpm-helloword-1.1.0/error/parentroot ext4 rw,relatime 0 0
 /proc /obswrk/root/home/abuild/rpmbuild/BUILD/rpm-helloword-1.1.0/error/proc proc rw,relatime 0 0
 none /obswrk/root/my\040dir proc rw,relatime 0 0
 none /obswrk/root/my\134040dir2 proc rw,relatime 0 0
 none /obswrk/root/1\040\134n\0402 proc rw,relatime 0 0
```

Execution steps of umount_stuff running with `bash -x`:
```
[   89s] + umount_stuff
[   89s] + test -n /obswrk/root -a /obswrk/root '!=' /
[   89s] + read -r mountpoint
[   89s] ++ awk '{print length($2) " " $2}'
[   89s] ++ sort -r -n
[   89s] ++ cut -d ' ' -f 2-
[   89s] ++ grep '^/obswrk/root'
[   89s] ++ printf /obswrk/root/home/abuild/rpmbuild/BUILD/rpm-helloword-1.1.0/error/parentroot
[   89s] + umount -n /obswrk/root/home/abuild/rpmbuild/BUILD/rpm-helloword-1.1.0/error/parentroot
[   89s] + read -r mountpoint
[   89s] ++ printf /obswrk/root/home/abuild/rpmbuild/BUILD/rpm-helloword-1.1.0/error/proc
[   89s] + umount -n /obswrk/root/home/abuild/rpmbuild/BUILD/rpm-helloword-1.1.0/error/proc
[   89s] + read -r mountpoint
[   89s] ++ printf /obswrk/root/home/abuild/rpmbuild/BUILD/rpm-helloword-1.1.0/error
[   89s] + umount -n /obswrk/root/home/abuild/rpmbuild/BUILD/rpm-helloword-1.1.0/error
[   90s] + read -r mountpoint
[   90s] ++ printf '/obswrk/root/1\040\134n\0402'
[   90s] + umount -n '/obswrk/root/1 \n 2'
[   90s] + read -r mountpoint
[   90s] ++ printf '/obswrk/root/my\134040dir2'
[   90s] + umount -n '/obswrk/root/my\040dir2'
[   90s] + read -r mountpoint
[   90s] ++ printf '/obswrk/root/my\040dir'
[   90s] + umount -n '/obswrk/root/my dir'
[   90s] + read -r mountpoint
[   90s] ++ printf /obswrk/root/dev/shm
[   90s] + umount -n /obswrk/root/dev/shm
[   90s] + read -r mountpoint
[   90s] ++ printf /obswrk/root/dev/pts
[   90s] + umount -n /obswrk/root/dev/pts
[   90s] + read -r mountpoint
[   90s] ++ printf /obswrk/root/dev/pts
[   90s] + umount -n /obswrk/root/dev/pts
[   90s] + read -r mountpoint
[   90s] ++ printf /obswrk/root/dev/pts
[   90s] + umount -n /obswrk/root/dev/pts
[   90s] + read -r mountpoint
[   90s] ++ printf /obswrk/root/proc
[   90s] + umount -n /obswrk/root/proc
[   90s] + read -r mountpoint
[   90s] ++ printf /obswrk/root/sys
[   90s] + umount -n /obswrk/root/sys
[   90s] + read -r mountpoint
```

**Comment by marcus-h** [comment]
On 2020-11-24 03:40:24 -0800, kvelichko-omp wrote:
> diff --git a/build b/build
> index 7725e070..b57ce064 100755
> --- a/build
> +++ b/build
> @@ -799,7 +799,7 @@ mount_stuff() {
>  umount_stuff() {
>      if test -n "$BUILD_ROOT" -a "$BUILD_ROOT" != / ; then
>  	while read -r mountpoint; do
> -	    umount -n $mountpoint 2>/dev/null || true
> +	    umount -n "$(printf $mountpoint)" 2>/dev/null || true
>  	done < <(awk '{print length($2) " " $2}' < /proc/mounts | sort -r -n | cut -d ' ' -f 2- | grep "^$BUILD_ROOT")
>      fi
>  }

Hmm it is still possible to umount stuff from the host system:

sudo mkdir /zzz$'\x0a'
sudo ln -s /mnt /zzz
sudo mount -t proc none /zzz$'\x0a'

In this case /mnt will be umounted because $(...) strips trailing
newlines.

I'm not really sure if it is worth the effort to umount stuff, which
is not explicitly set up by the build script itself. For instance,
you can also fool around with "ip addr ...", which might have some
effect on the host system or a subsequent build - we won't "undo"
such stuff either. If such "nasty" things can happen during your
chroot based builds, you are probably better off if you build in a
VM.

**Comment by kvelichko-omp** [comment]
We are trying to stop using kvm because our workers run in WMWare vCloud already on virtual machines. Also, qemu-arm is launched during build. The result is 3 levels of virtualization. By eliminating the use of kvm, we speed up the build process by 10-20 seconds for each package.

The problem is not that mounted directories remain in the system. Circular mount problem. :
```
sudo mount -o loop image.img error/
sudo mount -o loop image.img error/parentroot
```
This raises an error the next time assemblies are run on this worker. And if the package is rebuilt several times, then all the workers can be destroyed.

I execut build with:
```
sudo mkdir /zzz$'\x0a'
sudo ln -s /mnt /zzz
sudo mount -t proc none /zzz$'\x0a'
```
It can not umount path zzz but host mounts not umounted also:
```
[  100s] + umount_stuff
[  100s] + test -n /obswrk/root -a /obswrk/root '!=' /
[  100s] + read -r mountpoint
[  100s] ++ awk '{print length($2) " " $2}'
[  100s] ++ sort -r -n
[  100s] ++ cut -d ' ' -f 2-
[  100s] ++ grep '^/obswrk/root'
[  100s] ++ printf /obswrk/root/home/abuild/rpmbuild/BUILD/rpm-helloword-1.1.0/error/parentroot
[  100s] + umount -n /obswrk/root/home/abuild/rpmbuild/BUILD/rpm-helloword-1.1.0/error/parentroot
[  100s] + read -r mountpoint
[  100s] ++ printf /obswrk/root/home/abuild/rpmbuild/BUILD/rpm-helloword-1.1.0/error/proc
[  100s] + umount -n /obswrk/root/home/abuild/rpmbuild/BUILD/rpm-helloword-1.1.0/error/proc
[  100s] + read -r mountpoint
[  100s] ++ printf /obswrk/root/home/abuild/rpmbuild/BUILD/rpm-helloword-1.1.0/error
[  100s] + umount -n /obswrk/root/home/abuild/rpmbuild/BUILD/rpm-helloword-1.1.0/error
[  100s] + read -r mountpoint
[  100s] ++ printf '/obswrk/root/1\040\134n\0402'
[  100s] + umount -n '/obswrk/root/1 \n 2'
[  100s] + read -r mountpoint
[  100s] ++ printf '/obswrk/root/my\134040dir2'
[  100s] + umount -n '/obswrk/root/my\040dir2'
[  100s] + read -r mountpoint
[  100s] ++ printf '/obswrk/root/my\040dir'
[  100s] + umount -n '/obswrk/root/my dir'
[  100s] + read -r mountpoint
[  100s] ++ printf '/obswrk/root/zzz\012'
[  100s] + umount -n /obswrk/root/zzz
[  100s] + true
[  100s] + read -r mountpoint
[  100s] ++ printf /obswrk/root/dev/shm
[  100s] + umount -n /obswrk/root/dev/shm
[  100s] + read -r mountpoint
[  100s] ++ printf /obswrk/root/dev/pts
[  100s] + umount -n /obswrk/root/dev/pts
[  100s] + read -r mountpoint
[  100s] ++ printf /obswrk/root/dev/pts
[  100s] + umount -n /obswrk/root/dev/pts
[  100s] + read -r mountpoint
[  100s] ++ printf /obswrk/root/dev/pts
[  100s] + umount -n /obswrk/root/dev/pts
[  100s] + read -r mountpoint
[  100s] ++ printf /obswrk/root/proc
[  100s] + umount -n /obswrk/root/proc
[  100s] + read -r mountpoint
[  100s] ++ printf /obswrk/root/sys
[  100s] + umount -n /obswrk/root/sys
[  100s] + read -r mountpoint
```

As a result, the folder was not unmounted. But nothing tried to unmount on the host system either.

**Comment by marcus-h** [comment]
On 2020-11-24 08:44:08 -0800, kvelichko-omp wrote:
> We are trying to stop using kvm because our workers run in WMWare vCloud already on virtual machines. Also, qemu-arm is launched during build. The result is 3 levels of virtualization. By eliminating the use of kvm, we speed up the build process by 10-20 seconds for each package.
>
Hmm ok:/

> The problem is not that mounted directories remain in the system. Circular mount problem. :
> ```
> sudo mount -o loop image.img error/
> sudo mount -o loop image.img error/parentroot
> ```
> This raises an error the next time assemblies are run on this worker. And if the package is rebuilt several times, then all the workers can be destroyed.
>
Hmm you could also kill the worker if you do something like

for i in $(seq 32768); do
    sudo kill -9 $i
done

in a chroot based build.

> I execut build with:
> ```
> sudo mkdir /zzz$'\x0a'
> sudo ln -s /mnt /zzz
> sudo mount -t proc none /zzz$'\x0a'
> ```
> It can not umount path zzz but host mounts not umounted also:

Well if something is mounted on /mnt on the host, it will be umounted:

> [  100s] + read -r mountpoint
> [  100s] ++ printf '/obswrk/root/zzz\012'
> [  100s] + umount -n /obswrk/root/zzz

Since /obswrk/root/zzz is a symlink to /mnt, /mnt will be umounted.


Another remark about the patch:

> +	done < <(awk '{print length($2) " " $2}' < /proc/mounts | sort -r -n | cut -d ' ' -f 2- | grep "^$BUILD_ROOT")

The grep might cause some trouble if several workers run on the same host:
- buildroot of worker 1:  /obswork/root_1
- buildroot of worker 11: /obswork/root_11

**Pull request closed without merging**
