### PR TITLE
Adds Debian configurations

### PR DESCRIPTION
**Pull request by alee-ccu**
Add configuration for Debian Unstable and Jessie.

Author: Héctor Orón Martínez <zumbi@debian.org>
Signed-off-by: Andrew Lee (李健秋) <ajqlee@debian.org>

### CODE REVIEW

**Comment by alee-ccu** [comment]
Hi. I am obs-build package maintainer in Debian:
  https://tracker.debian.org/pkg/obs-build

We currently has this patch included in our Debian package to be able to build a full distro.
  https://sources.debian.org/src/obs-build/20180302-3/debian/patches/add-debian-unstable-and-jessie-configs.patch/

As a maintainer's point of view. I wish this could be included in upstream.

**Comment by adrianschroeter** [comment]
"unstable" is a quite generic name, could you rename it to "debian_unstable" maybe?
Maybe doing the  same for "jessie" to stay consistent.

**Comment by alee-ccu** [comment]
Okay. Renamed them as
  configs/debian-jessie.conf
  configs/debian-unstable.conf

**Comment by adrianschroeter** [comment]
thanks!

**Pull request merged**
