### PR TITLE
Add support of Debian Source format 3.0 (quilt)

### PR DESCRIPTION
**Pull request by ila-embsys**
This merge request contains changes to get a possibility to use Debian source format version 3.0 (quilt).

[Debian Manual](https://www.debian.org/doc/debian-policy/ch-controlfields.html#id26) describe supported format list:
"1.0, 3.0 (native), and 3.0 (quilt)". To pick differences, as the reference was used [the page](https://wiki.debian.org/Projects/DebSrc3.0) which summarizes how to switch source package formats.

Using this information, changes in the merge request is bringing to OBS's Debian source generator next:
 - Supports inclusion of binary files. It is done by the existing `Debtransform-Files` tag by keeping them in `*.debian.tar.gz` and passing `--include-binaries` to `dpkg-source`.
 - Debian-specific changes are no longer stored in a single `.diff.gz` but in multiple patches in `debian/patches/`. inside `*.debian.tar.gz`. Previously a file `debian.series` was used to make `.diff.gz`.

Key changes were done in `debtransform` file.
To keep the previous behaviour for 1.0, the script checks in necessary places format version in `*.dsc` and apply functions that are changed to specific for generating the new source format. Ex: Functions `doseries_quilt`, `dofile_quilt`, `dotar_quilt` for new format is used rather `doseries`, `dofile`, `dotar`.

Into the folder `test-debtransform`, similar to existing tests added the new test that was used to check the `debtransform` generator with the new source format.

### CODE REVIEW

**Comment by ila-embsys** [comment]
Resolves #225. Binary files were one of the reasons to start the work.
Possibly resolves #369. The merge request brings the new format but only `3.0 (quilt)`. It will not affect `3.0 (native)`.
Possibly resolves #500. Modified code that in this merge request was used to build Debian package with `install` Make target. An error with `dh_install` was not noticed.

**Comment by ila-embsys** [comment]
> IIRC recently support was added to avoid needing the .dsc file in the sources (given it's like the srpm, it's a generated output not an input), any chance to support that? The source format is recorded in the debian.tar in debian/source/format

I am, not sure I understand you. Maybe I provide not entirely accurate description.

There are two `*.dsc` files.

The first one is an input for the `debtransform`. It contains sections like 'DEBTRANSFORM-TAR' and 'DEBTRANSFORM-FILES'. I will call it a `dsc template`.
The second one is the output of the `debtransform`. It contains the section `Files` with references to a generated `*.orig.tar.gz` and `*.debian.tar.gz` archives. It is a true `*.dsc`. I will call it the `true dsc`.

So, a `dsc template` is passed to the `debtransform`. If the `debtransform` sees that in the `dsc template` the `Format` field has the value `3.0 (quilt)` then the `debtransform` generate three files: an `*.orig.tar.gz`, a `*.debian.tar.gz` and the `true dsc`. The `true dsc` is outside of generated sources. Also in the file `*.debian.tar.gz` in the path `debian/source/format` the `debtransform` writes the `3.0 (quilt)` value.

Is this the behaviour you have asked me about?

**Comment by bluca** [comment]
OBS can now work (AFAIK) without a .dsc in the source, as long as the standard debian/control file is available - that's what I'm referring to

**Comment by ila-embsys** [comment]
> OBS can now work (AFAIK) without a .dsc in the source, as long as the standard debian/control file is available - that's what I'm referring to

[Here is original repository](https://build.opensuse.org/package/show/home:ila.embsys/zephyr-sdk-ada) that I used to build the package when I worked on this merge request. How can I build it without a `dsc`? Even though there is `debian.control`.

This is my first attempt to package `deb` by OBS. I read the Debian Builds article section [Alternative method of creating a Debian package](https://en.opensuse.org/openSUSE:Build_Service_Debian_builds#openSUSE_prerequisites_to_build_.deb_packages). Have I miss some important? I gather sources by `obs_scm` then generate debian-tar + dsc by `debtransform` then build the package itself. I see only a way of prepare debian-tar manually by hand but it is not what I want.

**Comment by bluca** [comment]
Simply omit the .dsc file

**Comment by ila-embsys** [comment]
> Simply omit the .dsc file

I tried just omit `*.dsc` on remote repo. You are right, OBS is trying to build the package using `debian.control` file as a recipe.

Unfortunately, the build process failed because of `debian/changelog` is not found. Where should it be? On the root of the repo or on `*.debian.tar.gz`? I have tried to build the package in the same way locally without `*.dsc`. But my local runner didn't build the package with `debian.control` file as a recipe.

Can you provide more information on how to use the build without `*.dsc`?

**Comment by bluca** [comment]
> > Simply omit the .dsc file
> 
> I tried just omit `*.dsc` on remote repo. You are right, OBS is trying to build the package using `debian.control` file as a recipe.
> 
> Unfortunately, the build process failed because of `debian/changelog` is not found. Where should it be? On the root of the repo or on `*.debian.tar.gz`? I have tried to build the package in the same way locally without `*.dsc`. But my local runner didn't build the package with `debian.control` file as a recipe.
> 
> Can you provide more information on how to use the build without `*.dsc`? Is it documented anywhere?

That expects it to be in the root of the repository - ie, a standard Debian package repository layout.

But anyway, it was not my intention to block with PR - this is a great starting point, this feature can be improved later.

**Review by bluca — APPROVED** [review]

**Comment by ila-embsys** [comment]
> That expects it to be in the root of the repository - ie, a standard Debian package repository layout.
> 
> But anyway, it was not my intention to block with PR - this is a great starting point, this feature can be improved later.

I understood the idea. This is less related to the `debtransform` tool, and sure, can be improved later.

Thank you for the review. :)

**Comment by ila-embsys** [comment]
@adrianschroeter Can you look the request again? It is approved now.

**Pull request merged**
