### PR TITLE
More README.md edits

### PR DESCRIPTION
**Pull request by abitrolly**
* Add link to latest builds
* Fix typos

### CODE REVIEW

**Comment by abitrolly** [comment]
It is interesting why LXC is considered insecure?
And if LXD is secure for this purpose?

**Comment by abitrolly** [comment]
How `docker` builds are different that they provide limited reproducibility?

**Comment by adrianschroeter** [comment]
actually, I dunno anymore why LX? had problem some problem, but there is something in my memories. 
It would need a review by security people in any case to declare it secure. But we do not use it atm, so we have no priority on it.

(it is nothing against LXC as technology, but keep in mind that the build happens as root user, so there must be a more complete hardening as when running containers as normal user).

**Comment by adrianschroeter** [comment]
thanks a lot for your fixes!

**Comment by abitrolly** [comment]
Just saving time for future me. )

**Pull request merged**
