### PR TITLE
sl13.3.conf: Prepare for bash 4.4, using libreadline7

### PR DESCRIPTION
**Pull request by DimStar77**

### CODE REVIEW

**Comment by DimStar77** [comment]
This can be a bit messy in OBS I guess: the 'new' package with readline7 specified will fail to build while building against bash 4.3 - but Staging:B has bash 4.4 which fails with the current version of build

**Comment by adrianschroeter** [comment]
you are aware that these configs are only used for off-line build?
I assume that we need to sync them anyway to current openSUSE:Factory state, but they are not used inside of OBS.

**Comment by DimStar77** [comment]
Hmm.. in Staging:B I already set libreadline7 as THE version of readline to be used...

**Comment by DimStar77** [comment]
And the fail happens in the test suite - which likely tries to mimmick what would happen offline anyway:

```
[   41s] + ./testbuild.sh /.build.binaries/
[   41s] /usr/src/packages/BUILD/obs-build-20160809/build --root /abuild/build-root --repository /.build.binaries/
[   41s] logging output to /abuild/build-root/.build.log...
[   41s] [    0s] Memory limit set to 6814702KB
[   41s] [    0s] Using BUILD_ROOT=/abuild/build-root
[   41s] [    0s] Using BUILD_ARCH=x86_64:i686:i586:i486:i386
[   41s] [    0s] 
[   41s] [    0s] 
[   41s] [    0s] lamb16 started "build libdummy1.spec" at Tue Oct 25 07:46:34 UTC 2016.
[   41s] [    0s] 
[   41s] [    0s] 
[   41s] [    0s] processing recipe /usr/src/packages/BUILD/obs-build-20160809/test/libdummy1.spec ...
[   41s] [    0s] init_buildsystem --configdir /usr/src/packages/BUILD/obs-build-20160809/configs --cachedir /var/cache/build --repository /.build.binaries/ /usr/src/packages/BUILD/obs-build-20160809/test/libdummy1.spec ...
[   41s] [    0s] initializing /abuild/build-root/.srcfiles.cache ...
[   41s] [    0s] /usr/src/packages/BUILD/obs-build-20160809/createdirdeps --oldfile /abuild/build-root/.srcfiles.cache /.build.binaries/
[   42s] [    0s] expanding package dependencies...
[   42s] [    0s] Warning: distribution not specified, assuming 'default' (see /usr/src/packages/BUILD/obs-build-20160809/configs).
[   42s] [    0s] expansion error
[   42s] [    0s]   nothing provides libreadline6
[   42s] [    0s] 
[   42s] [    0s] lamb16 failed "build libdummy1.spec" at Tue Oct 25 07:46:34 UTC 2016.
[   42s] [    0s] 
[   42s] FAILED
```

**Comment by adrianschroeter** [comment]
right, wasn't aware that this problem existed.... thanks

**Pull request merged**
