### PR TITLE
Factory preinstall using dep expansion

### PR DESCRIPTION
**Pull request by adrianschroeter**
This is independend if the decision what we use in OBS.

### CODE REVIEW

**Comment by mlschroe** [comment]
Wait wait wait, this has to follow the openSUSE:Factory config. And you'll want to minimize the expanded preinstall list first.

**Comment by adrianschroeter** [comment]
IMHO it does not have to follow, since factory is anyway a moving target.

**Comment by mlschroe** [comment]
What's the point of this if it does not match? If you want this, please rename the config to "adrian.conf" or something like that.

**Comment by adrianschroeter** [comment]
the chances are higher that it matches with that change.... as the package lifes also in non-factory distros with that config file.

**Comment by adrianschroeter** [comment]
michael gave up on me:)

**Pull request merged**
