### PR TITLE
createzyppdeps repo type is not set anymore, rpm-md is assumed default

### PR DESCRIPTION
**Pull request by adrianschroeter**
boo#1174708

### CODE REVIEW

**Comment by mlandres** [comment]
You could as well test for the presence of a `repodata` dir (rpmmd) or a `content` file (yast). Otherwise it's proably a plaindir repo.

**Comment by adrianschroeter** [comment]
we would need to add support for plain dirs first ....

**Comment by mlandres** [comment]
Or let plaindir fail as it does now.

**Comment by mlschroe** [comment]
Fixed in a different way.

**Pull request closed without merging**
