### PR TITLE
dsc: Generate .changes files when building deb packages.

### PR DESCRIPTION
**Pull request by jpwhiting**
Include the changelog from the previous versions.
Add ~0 to use the current version in the changelog as well.

### CODE REVIEW

**Comment by jgeboski** [comment]
This breaks Debian builds for me.  Where is `DEBVERSION` ever defined?  Shouldn't this have been conditionalized in order to remain backward compatible?

```
[   40s] dpkg-deb: building package `bitlbee-facebook' in `../bitlbee-facebook_17~f55536c_i386.deb'.
[   40s]  dpkg-genchanges -v~0 >../bitlbee-facebook_17~f55536c_i386.changes
[   40s] parsechangelog/debian: warning: 'since' option specifies non-existing version
[   40s] parsechangelog/debian: warning: use newest entry that is earlier than the one specified
[   40s] parsechangelog/debian: error: parsechangelog/debian: error: ~0 is not a valid version
[   40s] 
[   40s] dpkg-genchanges: error: changelog parser /usr/lib/dpkg/parsechangelog/debian gave error exit status 255
[   40s] dpkg-buildpackage: error: dpkg-genchanges gave error exit status 255
```

**Comment by DrMcCoy** [comment]
As @jgeboski said, [this breaks basically all Debian and Ubuntu packages on the public OBS instance](http://lists.opensuse.org/opensuse-buildservice/2015-07/msg00023.html). :(

**Comment by adrianschroeter** [comment]
The change got reverted for now

**Comment by aneutrals** [comment]
@adrianschroeter Do you know when OBS will start using the reverted build script?

**Comment by adrianschroeter** [comment]
it is active since 5 hours

**Comment by jnweiger** [comment]
@adrianschroeter I believe there is more:
https://bugzilla.novell.com/show_bug.cgi?id=939398

**Comment by DrMcCoy** [comment]
Yeah, I [notice the same problem](http://lists.opensuse.org/opensuse-buildservice/2015-07/msg00028.html). :/

**Comment by HurricaneHernandez** [comment]
Same here.

**Comment by Artox** [comment]
is anyone considering to readd the -v parameter to dpkg-buildpackage?

I have just very unexpectedly been confronted with a
[  873s] E: debhelper changes: backports-changes-missing

which seems to suggest genrating the changes file at build-time

**Comment by Artox** [comment]
How about generating changes since version 0? I guess 0 is a safe value to assume.

The error jumping at me is not an error, backports-changes-missing is obsolete and was marked non-fatal in lintian 2.5.32

**Pull request merged**
