### PR TITLE
Don't bin existing BUILD dir on --no-init.

### PR DESCRIPTION
**Pull request by thorstenb**
Permits incremental building inside buildroot.

### CODE REVIEW

**Comment by adrianschroeter** [comment]
What exactly want you achieve here? rpmbuild would still remove this directory usually, no?

IMHO we should implement some "build --shell" option instead to jump inside. The user can call rpmbuild (or any other tool) directly with the stage options.

**Comment by marcus-h** [comment]
On 2015-03-03 00:12:13 -0800, Adrian Schr�ter wrote:
> What exactly want you achieve here? rpmbuild would still remove this directory usually, no?
> 
I think something like this makes sense if you want to examine e.g. build
failures in the build chroot/vm (using "build ... --shell" or
"osc build ... --shell").

> IMHO we should implement some "build --shell" option instead to jump inside. The user can call rpmbuild (or any other tool) directly with the stage options.
> 
The build script already has such an option (but it indirectly removes
the TOPDIR).

**Comment by thorstenb** [comment]
Sure, getting me a shell inside the build vm/chroot would permit that as well. Just that osc chroot does not currently seem to yield a functioning build environment.
But this patch is rather minimal, and enables me playing %setup -D -T 0 tricks. Otherwise fixing rpmlint problems in large projects (libreoffice, ceph) are pretty painful.

**Comment by mlschroe** [comment]
I changed the code so that it does not erase $TOPDIR if --no-init is given twice. That way we stay compatible to old versions.

**Comment by thorstenb** [comment]
Ah cool, that works. Thanks!

**Pull request closed without merging**
