### PR TITLE
Debian: fix conflict with Debian's osc and obs-build

### PR DESCRIPTION
**Pull request by bluca**
Debian ships build in a package named obs-build. Given the package names are different, but ship the same files, there is a conflict on the file system. This was sent via https://build.opensuse.org/request/show/450943 but it got lost when the files moved into git.

Also add symlinks so that build can work with Debian's version of osc out of the box.

### CODE REVIEW

**Comment by adrianschroeter** [comment]
hm, shouldn't we rename the package name in our builds then?

**Comment by bluca** [comment]
I can rename and take away the conflict/replace/provides if you are ok with that, give me a few mins

**Comment by bluca** [comment]
the symlinks will still be needed for full compatibility

**Comment by bluca** [comment]
@adrianschroeter done.

**Pull request merged**
