### PR TITLE
README.md: improve style, grammar and hyperlinks

### PR DESCRIPTION
**Pull request by yecril71pl**
This file looked like shit in Okular.

### CODE REVIEW

**Comment by adrianschroeter** [comment]
github shows chars like &mdash; ... can you avoid that?

**Comment by yecril71pl** [comment]
> github shows chars like — ... can you avoid that?

I am not sure what you mean.  The discussion shows rendered pause and ellipsis, not character reference codes.  I have replaced references to `&mdash;` with UTF&ndash;8; I normally try to avoid it because it makes the source hard to read.  Please advise.

**Comment by adrianschroeter** [comment]
I fixed it manually now, thanks.

**Comment by adrianschroeter** [comment]
erm, why did rebase get rid of your commit name? sorry, not itentional happen ...

will try to fix that ...

**Comment by adrianschroeter** [comment]
hm, that might happen, because I sign the commits ... will be a bit more careful the next time and keep an eye on it ...

**Comment by adrianschroeter** [comment]
but you are co-author now at least....

**Pull request closed without merging**
